theme: jekyll-theme-minimal
title: Understanding what makes a Wikipedia article popular
description: ADA And The Lovelace
show_downloads: True
  - title: Home
    url: /
  - title: Example
    url: example
