remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 
title: Understanding what makes a Wikipedia article popular
description: ADA And The Lovelace
show_downloads: True
navigation:
  - title: Home
    url: README
  - title: Example
    url: example
